from dataclasses import dataclass
from Options import Choice, OptionGroup, PerGameCommonOptions, Range, Toggle, OptionSet
from .AMQSongLibrary import OPTION_LIST

class QuizCount(Range):
    """
    How many quizzes to answer from
    You will need to clear every quiz in order to goal
    """
    display_name = "Quiz Count"
    range_start = 1
    range_end = 10
    default = 3

class QuizSongCount(Range):
    """
    How many songs total in each quiz
    """
    display_name = "Song Pool"
    range_start = 1
    range_end = 250
    default = 20

class RandomQuizTypes(OptionSet):
    """
    - Choose quiz categories that can be randomized
    - Currently available options: "Artist", "Composer", "Year"
    """
    display_name = "Random Quiz Types"
    valid_keys = ["Artist", "Composer", "Year"]
    default = ["Artist", "Composer", "Year"]

class QuizSelection(OptionSet):
    """
    These quizzes will be guaranteed to show up as part of your required goal.
    - 3 Categories currently: Artist, Composer, Year
    - Format as "Artist - Maaya Sakamoto"
    - A full list of options can be found in the options.txt file or with a search on anisongdb.com
    """
    display_name = "Include Quiz Type"
    valid_keys = {option for option in OPTION_LIST.keys()}
    default = ["Artist - Maaya Sakamoto", "Composer - Rasmus Faber", "Year - 1999"]

class QuizClear(Range):
    """
    What percentage correct needed per quiz to unlock the Final Quiz
    """
    display_name = "Quiz Clear Percentage"
    range_start = 50
    range_end = 100
    default = 70

class FinalQuizSongCount(Range):
    """
    How many songs total in final (goal) quiz
    The Final Quiz's song selection is a combination of every song
    generated by your individual quizzes
    """
    display_name = "Final Quiz Song Pool"
    range_start = 20
    range_end = 250
    default = 100

class FinalQuizGoal(Range):
    """
    What percentage correct needed in Final Quiz to goal
    """
    display_name = "Final Quiz Goal Percentage"
    range_start = 50
    range_end = 100
    default = 70

class GuessTime(Range):
    """
    Guess Time per song
    """
    display_name = "Guess Time"
    range_start = 1
    range_end = 60
    default = 20

class StartingSongs(Range):
    """
    How many songs you start with across all generated quizzes
    """
    display_name = "Starting Song Pool"
    range_start = 1
    range_end = 10
    default = 1

class Traps(Range):
    """
    Traps Percentage
    Includes user-submitted traps
    """
    display_name = "Traps Percentage"
    range_start = 0
    range_end = 100
    default = 10

@dataclass
class AMQOptions(PerGameCommonOptions):
    quiz_number: QuizCount
    random_quiz_types: RandomQuizTypes
    include_quiz_types: QuizSelection
    quiz_song_count: QuizSongCount
    quiz_goal: QuizClear
    final_quiz_song_count: FinalQuizSongCount
    final_quiz_goal: FinalQuizGoal
    guess_time: GuessTime
    starting_song_count: StartingSongs
    traps_percentage: Traps


